Repository Tudwall/Storyteller, pull requests merged in 2021-08, with the labels that each got.

#57 add font fallbacks
  src/styles/index.css
Labels: bug, style

#50 create storyIntro factory function
  src/js/story-intro.js
Labels: enhancement

#69 Changed kite image and chapter text
  src/images/dnd/1.3/kite-pink.svg
  src/images/dnd/1.3/kite-white.svg
  src/js/stories/1/chapters.js
  src/js/stories/1/images-setup.js
Labels: bug

#67 Added support for text only chapters
  src/js/chapter-factory.js
  src/js/chapter-factory.test.js
  src/js/chapterDOM.js
  src/js/stories/kite-story.js
Labels: enhancement

#79 Style chapters with only text
  dist/main.js
  src/js/chapterDOM.js
  src/styles/index.css
Labels: bug, style

#77 Remove help button (as long as there is no help)
  dist/main.js
  src/js/starting-page.js
Labels: Minimalize

#80 Style story end page
  dist/main.js
  src/js/storyEnd.js
  src/styles/index.css
Labels: style

#84 Implement smooth drop
  src/js/drag-drop.js
  src/styles/index.css
Labels: style

#74 Fix quiz label
  src/js/quiz-component.js
Labels: bug

#60 Create chapter index
  src/js/chapter-factory.js
  src/js/chapterIndex.js
  src/js/index.js
  src/js/logic.js
  src/js/starting-page.js
  src/js/story-factory.js
  src/styles/index.css
Labels: enhancement

#70 Make home button work
  src/js/chapterDOM.js
  src/js/chapterEnd.js
  src/js/logic.js
  src/js/storyEnd.js
Labels: bug, enhancement

#86 Style quiz page
  dist/index.html
  src/js/quiz-component.js
  src/styles/index.css
Labels: enhancement, style

#88 Put draggables at random position
  dist/main.js
  src/js/chapterDOM.js
  src/js/stories/1/images-setup.js
Labels: enhancement

#98 fixed bugs related to chapterIndex
  src/js/chapterIndex.js
  src/js/logic.js
  src/js/storyEnd.js
Labels: bug

#85 Fix window resizing bug
  dist/main.js
  src/js/chapterDOM.js
  src/js/drag-drop.js
  src/styles/index.css
Labels: bug

#92 Add text to next chapter button
  src/js/chapterDOM.js
  src/js/chapterIndex.js
  src/styles/index.css
Labels: style

#81 Fix story quiz
  src/js/logic.js
  src/js/quiz-factory.js
  src/js/stories/kite-story.js
  src/js/story-factory.js
  src/js/success-message.js
Labels: bug, enhancement

#101 fixed next button and quiz bugs
  src/js/logic.js
  src/js/quiz-component.js
  src/js/quiz-factory.js
  src/js/story-factory.js
Labels: bug

#106 Add help video to start page
  dist/47a634d35903457f3ebeb2115c14b26a.mp4
  dist/main.js
  dist/videos/help-video.mp4
  package-lock.json
  package.json
  src/help-video.mp4
  src/js/help.js
  src/js/starting-page.js
  src/styles/index.css
  webpack.config.js
Labels: enhancement

#109 Add styling for chapter index
  src/js/chapterIndex.js
  src/styles/index.css
Labels: style

#105 change #main-menu and #story-end sizes
  src/styles/index.css
Labels: style

#103 add scale effect and cursor pointers to all the buttons without effects
  src/styles/index.css
Labels: style

#102 Create LICENSE
  LICENSE
Labels: documentation
