Repository Tudwall/Storyteller, pull requests merged in 2021-07, with the labels that each got.

#8 Setup webpack
  .gitignore
  .prettierignore
  .prettierrc.json
  babel.config.js
  dist/index.html
  dist/main.js
  dist/main.js.map
  package-lock.json
  package.json
  src/js/index.js
  src/styles/index.css
  src/styles/reset.css
  webpack.config.js
Labels: enhancement

#7 Implement drag functionality
  src/js/drag-drop.js
Labels: enhancement

#11 Webpack scripts
  package.json
  webpack.config.js
Labels: enhancement

#13 Starting page
  src/js/starting-page.js
Labels: enhancement

#9 Implement dropping functionality
  src/js/drag-drop.js
Labels: enhancement

#17 added chapterEnd component
  src/js/chapterEnd.js
Labels: enhancement

#25 Adjust dropping math for circle
  src/js/drag-drop.js
Labels: enhancement

#31 Add render function
  src/js/render.js
Labels: enhancement

#24 added story end page
  src/js/storyEnd.js
Labels: enhancement

#37 Implement quiz-factory functionality
  src/js/quiz-factory.js
  src/js/quiz-factory.test.js
Labels: enhancement

#27 Write chapter tests
  src/js/chapter-factory.js
  src/js/chapter-factory.test.js
Labels: enhancement

#39 Add dnd images
  src/images/dnd/1.1/building.svg
  src/images/dnd/1.1/house-red.svg
  src/images/dnd/1.1/pond.svg
  src/images/dnd/1.1/trees.svg
  src/images/dnd/1.2/book.svg
  src/images/dnd/1.2/fabric.svg
  src/images/dnd/1.2/newspaper.svg
  src/images/dnd/1.2/paper.svg
  src/images/dnd/1.3/kite-blue.svg
  src/images/dnd/1.3/kite-orange.svg
  src/images/dnd/1.3/kite-rainbow.svg
  src/images/dnd/1.3/kite-white.svg
  src/images/dnd/1.4/building-pink.svg
  src/images/dnd/1.4/hospital.svg
  src/images/dnd/1.4/house-blue.svg
  src/images/dnd/1.4/house-red.svg
  src/images/dnd/1.5/hammer.svg
  src/images/dnd/1.5/ladder.svg
  src/images/dnd/1.5/rope.svg
  src/images/dnd/1.5/stairs.svg
  webpack.config.js
Labels: enhancement, style

#36 Add stories factory module
  src/js/story-factory.js
Labels: enhancement

#32 Game logic
  src/js/chapter-factory.js
  src/js/chapterDOM.js
  src/js/chapterEnd.js
  src/js/demo-story.js
  src/js/drag-drop.js
  src/js/index.js
  src/js/logic.js
  src/js/starting-page.js
  src/styles/index.css
Labels: enhancement

#46 added first story and quizSummary
  src/js/quiz-factory.js
  src/js/stories/1/chapters.js
  src/js/stories/1/dnd.js
  src/js/stories/1/quiz.js
Labels: enhancement

#52 Style startPage
  dist/0819c46e8d81490a793b.png
  dist/main.js
  src/images/styling/parchment.png
  src/js/starting-page.js
  src/styles/index.css
Labels: enhancement, style

#53 Game logic quiz
  src/js/chapterDOM.js
  src/js/chapterEnd.js
  src/js/demo-story.js
  src/js/index.js
  src/js/logic.js
  src/js/quiz-component.js
  src/js/quiz-factory.js
  src/js/story-factory.js
  src/js/storyEnd.js
Labels: bug, enhancement
